---
abstract: 'Documentation and tools for using Platypus with the C++ programming language'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::CBuilder: '0'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Platypus-Lang-CPP
no_index:
  directory:
    - examples
provides:
  FFI::Platypus::Lang::CPP:
    file: lib/FFI/Platypus/Lang/CPP.pm
    version: '0.01'
requires:
  FFI::Platypus: '0.16'
  Parse::nm: '0'
  perl: '5.008001'
resources:
  bugtracker: http://github.com/plicease/FFI-Platypus-Lang-CPP/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/plicease/FFI-Platypus-Lang-CPP
version: '0.01'
